# data.py
from models import Artifact, Tablet

# -----------------------DB---------------------------
artifacts = [
    # 견고
    Artifact("방패술 교본", max_level=1, combo="견고", is_unique=False),
    Artifact("베고니아 향 주머니", max_level=1, combo="견고", is_unique=False),
    Artifact("은접시", max_level=2, combo="견고", is_unique=True, constraint='bottom'),
    Artifact("힘의 부적", max_level=3, combo="견고", is_unique=True),
    Artifact("가시 부적", max_level=3, combo="견고", is_unique=True),
    Artifact("리포스테 검 조각", max_level=5, combo="견고", is_unique=True),
    Artifact("버려진 금반지", max_level=2, combo="견고", is_unique=True),
    Artifact("석궁 화살통", max_level=3, combo="견고", is_unique=True),
    Artifact("유리 망치", max_level=3, combo="견고", is_unique=True),
    Artifact("전사의 증표", max_level=5, combo="견고", is_unique=True),
    Artifact("찌르기 교본", max_level=0, combo="견고", is_unique=True),
    Artifact("형광 부적", max_level=4, combo="견고", is_unique=True),
    Artifact("생명의 손길", max_level=3, combo="견고", is_unique=True),
    Artifact("아그마 투영검 190,191번", max_level=7, combo="견고", is_unique=True),
    Artifact("재장전용 나무 상자", max_level=4, combo="견고", is_unique=True),
    Artifact("청동거울 파편", max_level=3, combo="견고", is_unique=False),
    Artifact("토끼 마을 경비병 투구", max_level=3, combo="견고", is_unique=True),
    Artifact("황동거울 파편", max_level=3, combo="", is_unique=True),
    Artifact("겸손의 왕관", max_level=4, combo="견고", is_unique=True),
    Artifact("실드 메이트", max_level=5, combo="견고", is_unique=True),
    Artifact("절대반지", max_level=2, combo="견고", is_unique=True),
    Artifact("푸른 손목 보호대", max_level=5, combo="견고", is_unique=True),
    Artifact("신비한 무게 추", max_level=4, combo="견고", is_unique=True),
    # 그림자
    Artifact("연막", max_level=0, combo="그림자", is_unique=True, is_spell=True),
    Artifact("재주의 부적", max_level=1, combo="그림자", is_unique=False),
    Artifact("환록의 망토", max_level=2, combo="그림자", is_unique=True),
    Artifact("녹색 도복", max_level=3, combo="그림자", is_unique=True),
    Artifact("마법의 안경", max_level=3, combo="그림자", is_unique=True),
    Artifact("모형 부리", max_level=4, combo="그림자", is_unique=True),
    Artifact("부서진 사파이어", max_level=2, combo="그림자", is_unique=True),
    Artifact("여섯 잎 클로버", max_level=3, combo="그림자", is_unique=True),
    # 빙하
    Artifact("눈 결정 목걸이", max_level=2, combo="빙하", is_unique=True),
    Artifact("명석함의 부적", max_level=3, combo="빙하", is_unique=True),
    Artifact("아이스 볼트", max_level=1, combo="빙하", is_unique=True, is_spell=True),
    Artifact("프로슘 반지", max_level=5, combo="빙하", is_unique=True),
    Artifact("마법 당근", max_level=4, combo="빙하", is_unique=True, constraint='top'),
    Artifact("빙하의 메아리", max_level=3, combo="빙하", is_unique=True),
    Artifact("서리 단검", max_level=4, combo="빙하", is_unique=True, is_spell=True),
    Artifact("빙결충", max_level=5, combo="빙하", is_unique=True),
    Artifact("빙설덩굴", max_level=2, combo="빙하", is_unique=True),
    Artifact("애로우 레인", max_level=3, combo="빙하", is_unique=True, is_spell=True),
    Artifact("얼어버린 알", max_level=3, combo="빙하", is_unique=True),
    Artifact("얼음갈매기의 발", max_level=3, combo="빙하", is_unique=True),
    Artifact("푹신한 털장갑", max_level=4, combo="빙하", is_unique=True),
    Artifact("푸른 발톱", max_level=3, combo="빙하", is_unique=False),
    # 호수
    Artifact("말라버린 꽃", max_level=2, combo="호수", is_unique=False),
    Artifact("엔도디트의 문진", max_level=2, combo="호수", is_unique=False),
    Artifact("지푸라기 인형", max_level=2, combo="호수", is_unique=False),
    Artifact("매혹하는 루어", max_level=2, combo="호수", is_unique=False),
    Artifact("물주머니", max_level=3, combo="호수", is_unique=True),
    Artifact("스타 루비", max_level=2, combo="호수", is_unique=False),
    Artifact("스타 아쿠아마린", max_level=2, combo="호수", is_unique=False),
    Artifact("오브러스의 피", max_level=3, combo="호수", is_unique=True),
    Artifact("부서진 나무뿌리", max_level=4, combo="호수", is_unique=True),
    Artifact("인공정령 이피엘", max_level=5, combo="호수", is_unique=True),
    Artifact("하얀 나뭇가지", max_level=4, combo="호수", is_unique=True),
    Artifact("하트모양 당근", max_level=4, combo="호수", is_unique=True),
    # 바람노래
    Artifact("바람풀 목도리", max_level=3, combo="바람노래", is_unique=True),
    Artifact("압박 밴드", max_level=2, combo="바람노래", is_unique=True),
    Artifact("가시덤불", max_level=4, combo="바람노래", is_unique=True, constraint='inside'),
    Artifact("금빛 망토", max_level=2, combo="바람노래", is_unique=True),
    Artifact("악보 '바람'", max_level=4, combo="바람노래", is_unique=True),
    Artifact("팔라스의 카드", max_level=4, combo="바람노래", is_unique=True),
    Artifact("헤이스트", max_level=2, combo="바람노래", is_unique=True, is_spell=True),
    Artifact("헬레나의 계단 모형", max_level=5, combo="바람노래", is_unique=True),
    Artifact("검술 교본", max_level=2, combo="바람노래", is_unique=True, constraint='top'),
    Artifact("격려의 깃발", max_level=2, combo="바람노래", is_unique=False),
    Artifact("바람노래", max_level=4, combo="바람노래", is_unique=False),
    Artifact("날개", max_level=5, combo="바람노래", is_unique=True),
    Artifact("무지갯빛 깃털", max_level=2, combo="바람노래", is_unique=True),
    # 신비
    Artifact("조화의 수정", max_level=1, combo="신비", constraint='harmony' ,is_unique=False),
    Artifact("강화 포션 뚜껑", max_level=0, combo="신비", is_unique=True),
    Artifact("대축복", max_level=2, combo="신비", is_unique=True, is_spell=True),
    Artifact("순백의 망토", max_level=5, combo="신비", is_unique=True),
    Artifact("용골 파편", max_level=3, combo="신비", is_unique=True, constraint='edge'),
    Artifact("은팔찌", max_level=3, combo="신비", is_unique=True),
    Artifact("호박석", max_level=3, combo="신비", is_unique=True),
    Artifact("다용도 벨트", max_level=3, combo="신비", is_unique=True, constraint={'bottom', 'top_count'}),
    Artifact("푸른 고리", max_level=2, combo="신비", is_unique=True),
    Artifact("하얀 알 껍질", max_level=4, combo="신비", is_unique=True),
    Artifact("혈석 반지", max_level=2, combo="신비", is_unique=True),
    Artifact("친타마니 돌", max_level=0, combo="신비", is_unique=True),
    Artifact("충격 증폭기", max_level=14, combo="신비", is_unique=True),
    # 마법공학
    Artifact("라이트닝 볼트", max_level=1, combo="마법공학", is_unique=True, is_spell=True),
    Artifact("반딧불이", max_level=2, combo="마법공학", is_unique=True),
    Artifact("번개 부메랑", max_level=4, combo="마법공학", is_unique=True, is_spell=True),
    Artifact("썬더의 귀걸이", max_level=5, combo="마법공학", is_unique=True),
    Artifact("전격 차크람", max_level=4, combo="마법공학", is_unique=True),
    Artifact("기린의 뿔", max_level=2, combo="마법공학", is_unique=True),
    Artifact("찌릿충", max_level=5, combo="마법공학", is_unique=True),
    Artifact("천둥 갑옷", max_level=4, combo="마법공학", is_unique=True, is_spell=True),
    Artifact("뇌운추적 나침반", max_level=3, combo="마법공학", is_unique=True),
    Artifact("전격의 부적", max_level=3, combo="마법공학", is_unique=False),
    # 얼음무구
    Artifact("눈보라 망치", max_level=5, combo="얼음무구", is_unique=True),
    Artifact("아이스 스타", max_level=5, combo="얼음무구", is_unique=True),
    Artifact("작은 마법 고둥", max_level=2, combo="얼음무구", is_unique=True),
    Artifact("축사의 검집", max_level=6, combo="얼음무구", is_unique=True),
    Artifact("볼루스파", max_level=5, combo="얼음무구", is_unique=True),
    Artifact("얼어붙은 심장", max_level=7, combo="얼음무구", is_unique=False),
    Artifact("얼음 날개", max_level=7, combo="얼음무구", is_unique=True),
    # 행성
    Artifact("잿빛 행성", max_level=5, combo="행성", is_unique=True),
    Artifact("노란 행성", max_level=6, combo="행성", is_unique=True),
    Artifact("붉은 행성", max_level=6, combo="행성", is_unique=True),
    Artifact("푸른 행성", max_level=5, combo="행성", is_unique=True),
    Artifact("하늘색 행성", max_level=5, combo="행성", is_unique=True),
    Artifact("거대 망원경", max_level=1, combo="행성", is_unique=False),
    Artifact("하얀 행성", max_level=7, combo="행성", is_unique=True),
    Artifact("암흑 행성", max_level=4, combo="행성", is_unique=True),
    # 정밀
    Artifact("부정한 붕대", max_level=3, combo="정밀", is_unique=True),
    Artifact("붉은 이슬", max_level=3, combo="정밀", is_unique=True),
    Artifact("열망의 부적", max_level=3, combo="정밀", is_unique=True),
    Artifact("초록색 톱니", max_level=0, combo="정밀", is_unique=True),
    Artifact("만화경", max_level=4, combo="정밀", is_unique=False),
    Artifact("발리송", max_level=3, combo="정밀", is_unique=True),
    Artifact("샤프 아이", max_level=2, combo="정밀", is_unique=True, is_spell=True),
    Artifact("쿠나이", max_level=2, combo="정밀", is_unique=True),
    Artifact("검 귀고리", max_level=3, combo="정밀", is_unique=True),
    Artifact("교만의 금관", max_level=4, combo="정밀", is_unique=True),
    Artifact("도서관 분침 미니어처", max_level=2, combo="정밀", is_unique=True),
    Artifact("따뜻한 돌", max_level=3, combo="정밀", is_unique=True, constraint='inside'),
    Artifact("뾰족한 방망이", max_level=2, combo="정밀", is_unique=True),
    Artifact("검은 비늘", max_level=3, combo="정밀", is_unique=True),
    Artifact("발터의 작업용 단안경", max_level=4, combo="정밀", is_unique=True),
    Artifact("베루트의 낫", max_level=3, combo="정밀", is_unique=True),
    # 동료
    Artifact("간이 계약서", max_level=4, combo="동료", is_unique=True),
    Artifact("금빛 핸드벨", max_level=4, combo="동료", is_unique=True, is_unit=True),
    Artifact("헌신의 휘장", max_level=3, combo="동료", is_unique=True),
    Artifact("고용 문장 '콜린'", max_level=2, combo="동료", is_unique=True, is_unit=True),
    Artifact("알폰소의 뿔", max_level=7, combo="동료", is_unique=True),
    Artifact("얇은 방석", max_level=6, combo="동료", is_unique=True),
    Artifact("채굴작업 총괄 완장", max_level=4, combo="동료", is_unique=True, is_unit=True),
    # 잉걸불
    Artifact("오히아 레후아", max_level=2, combo="잉걸불", is_unique=True),
    Artifact("파이어 볼트", max_level=1, combo="잉걸불", is_unique=True, is_spell=True),
    Artifact("발화 기름", max_level=3, combo="잉걸불", is_unique=True),
    Artifact("봉황의 날개짓", max_level=2, combo="잉걸불", is_unique=False),
    Artifact("붉은 뱀의 눈", max_level=5, combo="잉걸불", is_unique=True, is_spell=True),
    Artifact("사포테 열매", max_level=3, combo="잉걸불", is_unique=False),
    Artifact("신갈나무 숯", max_level=4, combo="잉걸불", is_unique=False),
    Artifact("용연향", max_level=4, combo="잉걸불", is_unique=False),
    Artifact("파이어 애로우", max_level=2, combo="잉걸불", is_unique=True, is_spell=True),
    Artifact("화염 가리개", max_level=2, combo="잉걸불", is_unique=True),
    Artifact("불 서커스", max_level=3, combo="잉걸불", is_unique=True, is_spell=True),
    Artifact("붉은 실뭉치", max_level=4, combo="잉걸불", is_unique=True),
    Artifact("화염초 뿌리", max_level=2, combo="잉걸불", is_unique=True),
    Artifact("화염충", max_level=5, combo="잉걸불", is_unique=True),
    Artifact("마그마 구슬", max_level=3, combo="잉걸불", is_unique=True),
    Artifact("메테오 샤워", max_level=3, combo="잉걸불", is_unique=True, is_spell=True),
    # 먹구름
    Artifact("돛대 모형", max_level=2, combo="먹구름", is_unique=False),
    Artifact("석화", max_level=1, combo="먹구름", is_unique=False),
    Artifact("찌릿 슈크림빵", max_level=2, combo="먹구름", is_unique=True),
    Artifact("구름 병", max_level=5, combo="먹구름", is_unique=False),
    Artifact("구름씨 화살촉", max_level=5, combo="먹구름", is_unique=False),
    Artifact("뾰족 도토리", max_level=3, combo="먹구름", is_unique=True),
    Artifact("잎새 가죽", max_level=3, combo="먹구름", is_unique=False),
    Artifact("번갯돌", max_level=6, combo="먹구름", is_unique=False),
    Artifact("뇌문 점토판", max_level=4, combo="먹구름", is_unique=True),
    Artifact("피뢰침", max_level=4, combo="먹구름", is_unique=True),
    # 수호
    Artifact("보호막", max_level=1, combo="수호", is_unique=True, is_spell=True),
    Artifact("천 갑옷", max_level=1, combo="수호", is_unique=False),
    Artifact("가시 등껍질", max_level=2, combo="수호", is_unique=True),
    Artifact("깨진 거울", max_level=1, combo="수호", is_unique=True),
    Artifact("방패 귀고리", max_level=3, combo="수호", is_unique=True),
    Artifact("냄비 뚜껑", max_level=5, combo="수호", is_unique=True),
    Artifact("도마뱀 판금 갑옷", max_level=4, combo="수호", is_unique=True),
    Artifact("세렌의 휘갈긴 편지", max_level=2, combo="수호", is_unique=True),
    Artifact("손 거울", max_level=2, combo="수호", is_unique=True),
    Artifact("흰 테두리 빵", max_level=2, combo="수호", is_unique=True),
    # 아카데미
    Artifact("마법사의 동전", max_level=2, combo="아카데미", is_unique=True),
    Artifact("갈망의 보주", max_level=3, combo="아카데미", is_unique=True),
    Artifact("레이에 별조각", max_level=3, combo="아카데미", is_unique=False),
    Artifact("아그배나무 열매", max_level=2, combo="아카데미", is_unique=False),
    Artifact("쥐 마법사의 펜던트", max_level=1, combo="아카데미", is_unique=True),
    Artifact("진주 가루", max_level=2, combo="아카데미", is_unique=False),
    Artifact("마법의 정석", max_level=4, combo="아카데미", is_unique=True),
    Artifact("명상 서적", max_level=3, combo="아카데미", is_unique=True),
    Artifact("보석 갑옷", max_level=2, combo="아카데미", is_unique=True),
    Artifact("빛나는 모래시계", max_level=3, combo="아카데미", is_unique=False, constraint='right_spell_book'),
    Artifact("이각수 관", max_level=5, combo="아카데미", is_unique=True),
    Artifact("전투 마법사의 장갑", max_level=3, combo="아카데미", is_unique=True),
    Artifact("라일리의 회중시계", max_level=2, combo="아카데미", is_unique=True, constraint='bottom'),
    Artifact("비어 있는 검 손잡이", max_level=6, combo="아카데미", is_unique=True),
    # 교섭
    Artifact("크리톤의 인장", max_level=2, combo="교섭", is_unique=False),
    Artifact("황금 단풍잎", max_level=0, combo="교섭", is_unique=True),
    Artifact("행운의 메달", max_level=2, combo="교섭", is_unique=True),
    # 저주
    Artifact("무뎌진 방울", max_level=2, combo="저주", is_unique=True),
    Artifact("오잉크 주술사의 목걸이", max_level=4, combo="저주", is_unique=False),
    Artifact("붉은 천 조각", max_level=3, combo="저주", is_unique=True),
    Artifact("중화제 흑", max_level=3, combo="저주", is_unique=False),
    Artifact("초록 잉크병", max_level=3, combo="저주", constraint='edge' ,is_unique=False),
    # 태양검
    Artifact("솔리스 프라투", max_level=2, combo="태양검", is_unique=False),
    Artifact("영원의 화로", max_level=2, combo="태양검", is_unique=True),
    Artifact("고대 모루", max_level=3, combo="태양검", is_unique=True),
    Artifact("솔리스 데쿠사", max_level=3, combo="태양검", is_unique=True),
    Artifact("솔리스 파르보", max_level=4, combo="태양검", is_unique=True),
    Artifact("운철 어깨 장식", max_level=4, combo="태양검", is_unique=True),
    Artifact("물드는 노을 망토", max_level=4, combo="태양검", is_unique=True),
    Artifact("솔리스 데크리", max_level=6, combo="태양검", is_unique=True),
    Artifact("운철 귀걸이", max_level=2, combo="태양검", is_unique=True),
    # 무속성
    Artifact("축복", max_level=2, combo="", is_unique=True, is_spell=True),
    Artifact("차가운 자물쇠", max_level=4, combo="", is_unique=False, constraint='isolated'),
    Artifact("하얀 종이", max_level=1, combo="", is_unique=True, constraint='bridge'),
    Artifact("경고 문서", max_level=1, combo="", is_unique=True),
    Artifact("홍차 잎 주머니", max_level=2, combo="", is_unique=True),
    Artifact("혈석 귀걸이", max_level=3, combo="", is_unique=True),
    Artifact("캘세더니 열쇠", max_level=3, combo="", is_unique=True),
    # 이중 콤보
    Artifact("미니 발리스타", max_level=4, combo={"먹구름", "동료"}, is_unique=True, is_unit=True),
    Artifact("바람개비", max_level=2, combo={"바람노래", "그림자"}, is_unique=True),
    Artifact("아마드의 영혼 가루", max_level=4, combo={"동료", "마법공학"}, is_unique=True, is_unit=True),
    Artifact("테로의 영혼 가루", max_level=5, combo={"동료", "잉걸불"}, is_unique=True, is_unit=True),
    Artifact("헤이타의 영혼 가루", max_level=4, combo={"동료", "빙하"}, is_unique=True, is_unit=True),
    Artifact("아카데미 브리건딘", max_level=5, combo={"수호", "아카데미"}, is_unique=True),
    # 결속 아티팩트
    Artifact("대립의 천칭", max_level=5, combo={"잉걸불", "빙하"}, is_unique=True),
    Artifact("루비 브로치", max_level=3, combo={"먹구름", "잉걸불"}, is_unique=True),
    Artifact("바위코끼리", max_level=4, combo={"수호", "바람노래"}, is_unique=True),
    Artifact("방패 가방", max_level=3, combo={"수호", "아카데미"}, is_unique=True),
    Artifact("봉인된 테자스", max_level=3, combo={"잉걸불", "빙하"}, is_unique=True),
    Artifact("소리굽쇠", max_level=4, combo={"아카데미", "견고"}, is_unique=True),
    Artifact("악보 '은하'", max_level=2, combo={"행성", "바람노래"}, is_unique=True),
    Artifact("악보 '폭풍'", max_level=3, combo={"먹구름", "바람노래"}, is_unique=True),
    Artifact("얼음구름 나비", max_level=3, combo={"먹구름", "빙하"}, is_unique=True),
    Artifact("영원의 식", max_level=3, combo={"얼음무구", "태양검"}, is_unique=True),
    Artifact("일렁이는 눈", max_level=4, combo={"그림자", "정밀"}, is_unique=True),
    Artifact("전술 지침서", max_level=3, combo={"동료", "정밀"}, is_unique=True),
    Artifact("플럭스 결합기 Mk.2", max_level=3, combo={"먹구름", "동료"}, is_unique=True),
    Artifact("플리트비체의 물방울", max_level=0, combo={"얼음무구", "호수"}, is_unique=True),
    Artifact("영원한 겨울", max_level=3, combo={"빙하", "견고"}, is_unique=True),
]

tablets = [
    # 일반석판 common
    Tablet("건조", directions=[(-6, 1), (6, 1)], turnable=False, tier='common'),
    Tablet("근사", directions=[(-6, 1), (1, 1)], turnable=True, tier='common'),
    Tablet("기사도", directions=[(-13, 1)], turnable=True, tier='common'),
    Tablet("도래", directions=[(-2, -1), (-1, -1), (1, 1), (2, 1)], turnable=True, tier='common'),
    Tablet("선의", directions=[(-1, 1), (6, 1)], turnable=False, constraint='bottom', tier='common'),
    Tablet("시선", directions=[(-7, 1), (7, -1)], turnable=True, tier='common'),
    Tablet("악수", directions=[(-1, 1), (1, 1)], turnable=True, tier='common'),
    Tablet("운명", directions=[(6, 1)], turnable=False, tier='common'),
    Tablet("재치", directions=[(-7, 1)], turnable=True, tier='common'),
    Tablet("착취", directions=[(-1, -1), (1, 1)], turnable=True, tier='common'),
    Tablet("화합", directions=[(-6, -1), (-1, 1), (1, 1), (6, 1)], turnable=True, tier='common'),
    Tablet("환호", directions=[(-6, 1)], turnable=False, tier='common'),
    Tablet("희망", directions=[(1, 1)], turnable=True, tier='common'),
    # 고급석판 uncommon
    Tablet("경쟁", directions=[(-1, 2), (-5, -1), (1, -1)], turnable=True, tier='uncommon'),
    Tablet("고동", directions=[(-2, 2)], turnable=True, tier='uncommon'),
    Tablet("고양", directions=[(1, 'UNLOCK')], turnable=True, tier='uncommon'),
    Tablet("과거", directions=[(-7, 1), (-6, 1), (-5, 1), (1, 1)], turnable=True, tier='uncommon'),
    Tablet("미래", directions=[(-7, 1), (-6, 1), (-5, 1), (-1, 1)], turnable=True, tier='uncommon'),
    Tablet("분배", directions=[(-6, 1), (-1, 1), (1, 1), (6, 1)], turnable=True, tier='uncommon'),
    Tablet("삼두", directions=[(-6, 1), (-1, 1), (1, 1)], turnable=False, tier='uncommon'),
    Tablet("수확", directions=[(-1, 2), (1, 2)], turnable=True, tier='uncommon'),
    Tablet("쌍성", directions=[(-2, 2), (2, 2)], turnable=True, tier='uncommon'),
    Tablet("양육", directions=[(-5, 1), (-2, -1), (-1, -1), (1, 1), (7, 1)], turnable=True, tier='uncommon'),
    Tablet("열망", directions=[(-6, 2)], turnable=False, tier='uncommon'),
    Tablet("응집", directions=[('ROW', -1), (-6, 3)], turnable=True, tier='uncommon'),
    Tablet("입구", directions=[(-7, 1), (-6, 2), (-5, 1)], turnable=False, tier='uncommon'),
    Tablet("장난", directions=[(-7, 1), (-6, 1), (-5, 1), (-1, -1), (1, -1)], turnable=True, tier='uncommon'),
    Tablet("적재", directions=[(-2, 1), (-1, 1), (4, 1), (5, 1)], turnable=True, tier='uncommon'),
    Tablet("전이", directions=[('ROW', 1), ('COL', -1)], turnable=True, tier='uncommon'),
    Tablet("전진", directions=[(1, 1), (2, 1), (3, 1)], turnable=True, tier='uncommon'),
    Tablet("정의", directions=[('COL', 1)], turnable=False, constraint='left_or_right', tier='uncommon'),
    Tablet("준비", directions=[(-7, 1), (7, 1)], turnable=True, tier='uncommon'),
    Tablet("출구", directions=[(5, 1), (6, 2), (7, 1)], turnable=False, tier='uncommon'),
    Tablet("파도", directions=[(-7, 2), (-6, -1), (-1, -1)], turnable=True, tier='uncommon'),
    Tablet("헌정", directions=[(-7, 1), (-5, 1), (5, 1), (7, 1)], turnable=True, tier='uncommon'),
    Tablet("명예", directions=[(-6, 2), (-13, 1)], turnable=True, tier='uncommon'),
    # 희귀 석판 rare
    Tablet("기반", directions=[('ROW', 1)], turnable=False, tier='rare'),
    Tablet("권능", directions=[(-6, 1)], turnable=True, tier='rare'),
    Tablet("단절", directions=[(-6, 3), (-1, -1), (1, -1), (6, 3)], turnable=False, tier='rare'),
    Tablet("동시성", directions=[('COL', 1)], turnable=False, tier='rare'),
    Tablet("맹세", directions=[(-12, 2), (-6, 1), (-1, 1), (1, 1), (6, 1)], turnable=True, tier='rare'),
    Tablet("반항", directions=[('SLASH', 1)], turnable=True, tier='rare'),
    Tablet("이음", directions=[(-6, 2), (6, "UNLOCK")], turnable=True, tier='rare'),
    Tablet("차양", directions=[('BOTTOM', 1)], turnable=False, constraint='top', tier='rare'),
    # 전설 석판 legendary
    Tablet("가시", directions=[(-7, 1), (-6, 2), (-5, 1), (-1, 1), (1, 1), (5, 1), (6, 2), (7, 1)]
           , turnable=False, tier='legendary'),
    Tablet("경계", directions=[('TOP', 1), ('BOTTOM', 1)], turnable=False, tier='legendary'),
    Tablet("광휘", directions=[(-6, 2), ('ROW', 1), (6, 2)], turnable=True, tier='legendary'),
    Tablet("기적", directions=[('ROW', 1), ('COL', 1)], turnable=False, tier='legendary'),
    # 기적은 회전가능이지만 회전이 무의미하기에 turnable=False로 표시
    Tablet("백일몽", directions=[(-13, 1), (-11, 1), (-7, 1), (-5, 1), (5, 1), (7, 1), (11, 1), (13, 1)]
           , turnable=True, tier='legendary'),
    Tablet("압축", directions=[(1, 3), (2, 2), (3, 1)], turnable=True, tier='legendary'),
    Tablet("확신", directions=[(-6, 5)], turnable=True, tier='legendary'),
    Tablet("환대", directions=[(-1, 1), (-6, 2), (-1, "UNLOCK"), (2, "UNLOCK")], turnable=False, tier='legendary'),
    Tablet("확신", directions=[(-6, 5)], turnable=True, tier='legendary'),
    Tablet("용기", directions=[("BACKSLASH", 1), (-5, 2), (5, 2)], turnable=True, tier='legendary'),
    Tablet("평화", directions=[(-1, 3), (1, 3)], turnable=True, tier='legendary'),
]
# 이미지 필요: 환대, 용기, 평화, 명예
# 영원한 겨울, 행운의 메달, 중화제 흑, 초록 잉크병, 전격의 부적, 조화의 수정, 충격증폭기

